# Cloud Build pipeline that containerises the Next.js + LaTeX app and deploys it to Cloud Run.
# Customize substitutions below before running `gcloud builds submit`.
substitutions:
  _REGION: us-central1
  _SERVICE: job-hunt-email
  _REPOSITORY: job-hunt-email
  _TAG: latest

options:
  diskSizeGb: 200

steps:
  - id: pull-cache
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - "-c"
      - "docker pull us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest || true"

  - id: build-image
    name: gcr.io/cloud-builders/docker
    env:
      - DOCKER_BUILDKIT=1
    args:
      [
        "build",
        "--build-arg",
        "BUILDKIT_INLINE_CACHE=1",
        "--cache-from",
        "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest",
        "--secret",
        "id=env,src=.env.build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest",
        ".",
      ]

  - id: push-image
    name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}",
      ]

  - id: push-cache-tag
    name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest",
      ]

  - id: deploy-cloud-run
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE}"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--port"
      - "8080"
      - "--allow-unauthenticated"
      # __DYNAMIC_ARGUMENTS__

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest"
